---
title: "Research"
---

## Peer Reviewed Research

### Methodology

Brodeur, Abel (and >300 co-authors including Ryan C. Briggs). (accepted). Reproducibility and Robustness of Economics and Political Science Research. *Nature*.

Aczel, Balazs (and >400 co-authors including Ryan C. Briggs). (accepted). Investigating the Analytical Robustness of the Social and Behavioural Sciences. *Nature*.

Arel-Bundock, Vincent, Briggs, Ryan C., Doucouliagos, Hristos, Mendoza Aviña, Marco, and Stanley, T.D. (2026). [Quantitative Political Science Research is Greatly Underpowered](https://doi.org/10.1086/734279). *Journal of Politics*, 88(1), 36–46.

Heinzel, Mirko, Weaver, Cate, and Briggs, Ryan C. (2025). [Incentivizing Responses in International Organization Elite Surveys: Evidence from the World Bank](https://doi.org/10.1017/XPS.2023.39). *Journal of Experimental Political Science*, 12(1), 17–26.

### Foreign Aid & Development Studies

Briggs, Ryan C. (2024). [Beliefs, Values, and Practices in Development Studies](papers/Briggs (2024) Beliefs.pdf). *Journal of Development Studies*, 60(10), 1493–1510.

Briggs, Ryan C. (2021). [Why does aid not target the poorest?](papers/Briggs (2021) Aid poorest.pdf) *International Studies Quarterly*, 65(3), 739–752.

Briggs, Ryan C. (2020). [Results from single-donor analyses of project aid success seem to generalize pretty well across donors](papers/Briggs (2020) Generalize.pdf). *Review of International Organizations*, 15(4), 947–963.

Briggs, Ryan C. (2019). [Receiving foreign aid can reduce support for incumbent presidents](papers/Briggs (2019) Aid Incumbent.pdf). *Political Research Quarterly*, 72(3), 610–622.

Briggs, Ryan C. (2018). [Leaving no one behind? A new test of subnational aid targeting](papers/Briggs (2018) Leaving no one behind.pdf). *Journal of International Development*, 30(5), 904–910.

Briggs, Ryan C. (2018). [Poor targeting: A gridded spatial analysis of the degree to which aid reaches the poor in Africa](papers/Briggs (2018) Poor Targeting.pdf). *World Development*, 103, 133–148.

Briggs, Ryan C. (2017). [Does foreign aid target the poorest?](papers/Briggs (2017) Aid Target Poorest.pdf) *International Organization*, 71(1), 187–206.

Briggs, Ryan C. (2015). [The influence of aid changes on African election outcomes](papers/Briggs (2015) Election Outcomes.pdf). *International Interactions*, 41(2), 201–225.

Briggs, Ryan C. (2014). [Aiding and Abetting: Project Aid and Ethnic Politics in Kenya](papers/Briggs (2014) Aiding and Abetting.pdf). *World Development*, 64, 194–205.

Briggs, Ryan C. (2012). [Electrifying the base? Aid and incumbent advantage in Ghana](papers/Briggs (2012) Electrify the base.pdf). *The Journal of Modern African Studies*, 50(4), 603–624.

### African Politics

Briggs, Ryan C. (2021). [Power to Which People? Explaining how electrification targets voters across party rotations in Ghana](papers/Briggs (2021) Electrification.pdf). *World Development*, 141, 105391.

Aidoo, Kobina and Briggs, Ryan C. (2019). [Underpowered: Rolling blackouts in Africa disproportionately hurt the poor](papers/Aidoo & Briggs (2019).pdf). *African Studies Review*, 62(3), 112–131.

Berinzon, Maya and Briggs, Ryan C. (2019). [Measuring and explaining formal institutional persistence in French West Africa](papers/Berinzon & Briggs (2019).pdf). *The Journal of Modern African Studies*, 57(2), 183–202.

Briggs, Ryan C. (2017). [Explaining case selection in African politics research](papers/Briggs (2017) Af Pol Research.pdf). *Journal of Contemporary African Studies*, 35(4), 565–572.

Berinzon, Maya and Briggs, Ryan C. (2016). [Legal families without the laws: The fading of colonial law in French West Africa](papers/Berinzon & Briggs (2016) Penal Code.pdf). *American Journal of Comparative Law*, 64(2), 329–370.\
*Winner of the Hessel Yntema Prize for best article published in AJCL in 2016 by authors under 40.*

Briggs, Ryan C. and Weathers, Scott. (2016). [The other white man's burden? Gender & location in African politics scholarship](papers/Briggs & Weathers (2016) Gender and Location.pdf). *African Affairs*, 115(460), 466–489.

### Other

Briggs, Ryan C. and Solodoch, Omer. (2024). [Changes in perceptions of border security influence desired levels of immigration](papers/Briggs & Solodoch (2023).pdf). *Journal of Conflict Resolution*, 68(6), 1252–1275.

Briggs, Ryan C. (2020). [Canadians think that nearly all of us will be allowed back to work around August](papers/Briggs (2020) Covid-19.pdf). *Canadian Journal of Political Science*, 53(2), 245–251.

### Book Chapters

Briggs, Ryan C. (2024). [Aid Targeting](https://www.elgaronline.com/edcollchap/book/9781800886810/book-part-9781800886810-16.xml) in *The Handbook of Aid and Development*, edited by Desai, Raj and Devarajan, Shanta and Tobin, Jennifer, pp. 159–173.

## Work in Progress

Briggs, Ryan C. and Vivalt, Eva. [Are Impact Evaluations in Development Economics Underpowered?](https://osf.io/8hkc5/)

Briggs, Ryan C., Mellon, Jonathan, and Arel-Bundock, Vincent. [It must be very hard to publish null results](https://osf.io/preprints/socarxiv/zr5vf_v1).

## Selected Other Writing

Briggs, Ryan C. (2025). [Can We Trust Social Science Yet?](https://asteriskmag.com/issues/10/can-we-trust-social-science-yet) *Asterisk*.

Briggs, Ryan C. and Chris Rutty. (2023). [Why we should declare a formal 'Smallpox Eradication Day'](https://ottawacitizen.com/opinion/briggs-and-rutty-why-we-should-declare-a-formal-smallpox-eradication-day/wcm/1d73235f-4e5d-467c-b612-9ffd48d0d7fb/amp/). *Ottawa Citizen*.

Briggs, Ryan C. and Dario Sidhu. (2021). [It's giving season — how do you ensure your charitable donations will be used effectively?](https://www.thestar.com/opinion/contributors/2021/11/29/its-giving-season-how-do-you-ensure-your-charitable-donations-will-be-used-effectively.html) *The Toronto Star*.

Briggs, Ryan C. (2021). [Why does aid not target the poorest?](https://voxdev.org/topic/institutions-political-economy/why-does-aid-not-target-poorest) *VoxDev*.

Briggs, Ryan C. (2018). [Millions of Americans as destitute as the world's poorest? Don't believe it](https://www.vox.com/the-big-idea/2018/2/1/16959634/millions-americans-destitute-2-day-worlds-poorest-deaton-aid). *Vox.com*.
